### ISSUE TITLE
compilerArgs get overwritten

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle-java-modules#10] opened 2018-03-08 16:08 UTC
With the `org.gradle.java.experimental-jigsaw` plugin applied, the `compilerArgs` get overridden instead of added.
This way you cannot do for example
```Groovy
tasks.withType(JavaCompile) {
   options.compilerArgs << '-proc:none'
   options.compilerArgs << '-Xmaxerrs' << '9999'
}
```
but you have to work-around it using
```Groovy
tasks.withType(JavaCompile) {
   options.compilerArgumentProviders << ({ ['-proc:none', '-Xmaxerrs', '9999'] } as CommandLineArgumentProvider)
}
```

Also it might not be a good idea to modify the `compilerArgs` inside `doFirst` at all as it works against incremental runs?

**Comment by rgoldberg** [comment] 2018-07-21 20:27
@Vampire 

I'm trying to implement some additional features & fixes for this plugin in a [fork](https://github.com/rgoldberg/gradle-java-modules).

I already append javac module args instead of replacing the existing args.

I don't think that modifying `compilerArgs` inside `doFirst` in this instance will cause issues for up-to-date checks for incremental task execution, because the `compilerArgs` changes just move dependencies from the class-path to the module-path (and sometimes add some other connecting javac args).

Maybe I'm wrong, though.

Do you have any examples of problems caused by moving the dependencies from `JavaCompile#getOptions()` to the module-path?

**Comment by Vampire** [comment] 2018-07-22 14:08
Well, e. g. if you do not have the plugin applied add then apply the plugin or the other way around. The task will not rerun while it should. Dunno about other instances, but in most cases it is a bad idea to change properties that should be part of up to date check during runtime I think.

Also consider instead of maintaining an own fork to contribute to or collaborate with https://github.com/zyxist/chainsaw.
It is also a fork of this plugin, fixed some things, added some features and the author is quite responsive, or at least we when I had issues.

**Comment by rgoldberg** [comment] 2018-07-22 15:04
Please see [my post on the Gradle Discussion Forum](https://discuss.gradle.org/t/how-does-a-composite-build-ensure-that-one-included-build-is-built-before-another/27711/6?u=rgoldberg) for issues I've had with Chainsaw.

It shouldn't be too hard to replicate the extra features from Chainsaw in my fork; hopefully, I'll get my commits merged via PR into the original Gradle repo.

I've already implemented:

1. supporting test frameworks other than JUnit 4
2. supporting javadoc
3. parsing the module name from `module-info.java` instead of requiring it to be duplicated in `javaModule.name` in `build.gradle(.kts)`
4. appending javac module arguments to existing arguments instead of replacing existing arguments
5. allowing source sets to not have a `module-info.java` (I'm not sure is Chainsaw already allowed this)

I've also already added the following features that I didn't see in Chainsaw:

1. compiling a `module-info.java` that exports a package that has no Java code, but that has code from another language (e.g., Kotlin)
2. only adding javac module arguments that include a path if that path is non-empty
3. general code cleanup, including using Gradle 4.9 Kotlin DSL (instead of 4.1 RC 1 Groovy DSL), updating dependency versions, using lambdas, etc.

I still need to implement the following features, either from Chainsaw, or new:

1. manually configuring various java tool module arguments (e.g., `--add-reads`)
2. optionally verifying module name standards compliance (i.e. module name = common package ancestor name)
3. optionally failing if `module-info.java` is missing

Did I miss any Chainsaw features?

**Comment by rgoldberg** [comment] 2018-07-22 15:54
I don't know Gradle internals too well, so sorry in advance if I don't know obvious Gradle use cases / pitfalls.

> Well, e. g. if you do not have the plugin applied add then apply the plugin or the other way around. The task will not rerun while it should.

Are plugins ever applied / enabled after the configuration phase?  If so, can you give me an example?

If plugins must be applied during the configuration phase, how would the Java tasks not be properly rerun?

All of these plugins aren't adding new dependencies, or removing existing ones, they're just changing how the dependencies are expressed to various Java tools like `javac`.  If X depends on Y, and Y is changed, then Y & X must be rebuilt regardless of Y being on the class-path or on the module-path.  The existing `AbstractCompile#classpath` property seems to provide the dependency linkage from X to Y, so leaving it intact until right before tasks for X are run should maintain the existing correct dependencies.

I can see an issue if a task can be rerun within a single Gradle execution, but I don't know why or how a task would be run more than once in a single Gradle execution.  Is it possible to run a task twice?

> or the other way around

What do you mean by that?  Do you mean that a plugin is applied and then somehow disabled?

The only issue I can see is if some other `doFirst` modifies or reads the class-path before or after the Java Module plugin's `doFirst` did, which could cause the Java Module plugin `doFirst`s and/or the other `doFirst`s to use the wrong class-path.  This can only be solved for all cases of class-path usage by all Gradle code & plugins keeping the class-path & module-path separate, but that would probably be a major breaking change to the core of Gradle.

**Comment by Vampire** [comment] 2018-07-22 17:09
I'm on mobile, not able to really look at code etc., but I think you understood me wrongly. 

No, there is no valid way I know of, to run a task multiple times during one build run.

What I meant was:

- do not have the plugin applied
- run the task
- apply the plugin via some way that does not change the build script classpath, e. g. apply it depending on a property value that is not registered as task input (made up example that probably doesn't make much sense, just to show the problem, there are most probably legit ways to have such a situation) 
- run the task again

As the inputs didn't change (task configuration is only changed during runtime), the task is considered up to date, while it would be necessary to rerun the task due to the changed configuration.

**Comment by rgoldberg** [comment] 2018-07-22 18:13
In that situation, I would hope that Gradle would notice that `Task#doFirst(...)` was called, and would therefore consider it not up-to-date.  If Gradle doesn't already do that, then that behavior should be added to core.

Even if Gradle core doesn't do that, for all but one of the `doFirst(Action)`s, `JigsawPlugin` calls `Task#getInputs().property("moduleName", moduleName)`, which should mark the `Task` as not up-to-date if the property wasn't previously set.  I'll have to ask why the original author didn't set the property for `javaCompile`.

Did you ever see any actual problem along the lines that you're describing, or is it a hypothetical problem?  If the former, hopefully it's a bug either introduced by Chainsaw, or already fixed by mode changes to the original plugin. If the latter, then hopefully it's a spurious issue.

**Comment by Vampire** [comment] 2018-07-22 22:54
Ah, you are right indeed.
Calling `doFirst()` should modify the custom actions and make the task out-of-date.
But as far as I remember this is even worse while I think about it.
Not for correctness, but for performance if you use the build cache.
As far as I remember, if you add custom actions (`doLast()`, `doFirst()`) to a cacheable task like `JavaDoc` or `JavaCompile`, then this makes the tasks uncacheable, so the build cache is not used anymore at all for this task. :-/

No, I don't think I had actual problems, just thought it might cause problems. Hence the "might not be a good idea" construct, as it is basically almost always a bad idea to modify the inputs of a task during runtime as far as my experience shows.

**Comment by jjohannes** [comment] 2020-05-04 09:52
Java Modules are supported directly in Gradle 6.4. Please open a new issue on https://github.com/gradle/gradle if there is still a problem.

**Closed as completed** 2020-05-04 09:52 UTC
