### ISSUE TITLE
Module naming standards compliance verification

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle-java-modules#32] opened 2018-08-11 17:39 UTC
Module naming standards compliance verification, i.e. ensure that module name = common package ancestor name.

Not really necessary, but supported by Chainsaw, so best to document it here in case others want this feature.

**Comment by jjohannes** [comment] 2020-05-04 10:21
Gradle 6.4 now has Module support built-in. Closing this as duplicate of https://github.com/gradle/gradle/issues/7752

**Closed as completed by jjohannes** 2020-05-04 10:21 UTC
